blueprint:
  name: Motion-Activated Light with Timer
  description: >
    Turn on lights or switches when motion is detected and turn them off after
    a specified delay. The timer resets each time motion is detected again.
    Optionally restrict operation to specific times of day.
  domain: automation
  input:
    motion_sensors:
      name: Motion Sensors
      description: Motion sensors or binary sensors that trigger the lights
      selector:
        entity:
          filter:
            - domain: binary_sensor
          multiple: true
    target_lights:
      name: Lights or Switches
      description: The lights or switches to control
      selector:
        target:
          entity:
            - domain: light
            - domain: switch
    no_motion_wait:
      name: Wait Time
      description: Time to wait after last motion before turning off
      default: 300
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
          mode: box
    time_restriction_enabled:
      name: Enable Time Restriction
      description: Only run during specified times
      default: false
      selector:
        boolean:
    start_time:
      name: Start Time
      description: Time to start allowing motion activation (ignored if time restriction disabled)
      default: "00:00:00"
      selector:
        time:
    end_time:
      name: End Time
      description: Time to stop allowing motion activation (ignored if time restriction disabled)
      default: "23:59:59"
      selector:
        time:

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input motion_sensors
    to: "on"

condition:
  - condition: template
    value_template: >
      {% set time_enabled = time_restriction_enabled %}
      {% if not time_enabled %}
        true
      {% else %}
        {% set current_time = now().strftime('%H:%M:%S') %}
        {% set start = start_time %}
        {% set end = end_time %}
        {% if start <= end %}
          {{ start <= current_time <= end }}
        {% else %}
          {{ current_time >= start or current_time <= end }}
        {% endif %}
      {% endif %}

action:
  - service: homeassistant.turn_on
    target: !input target_lights
  - wait_for_trigger:
      - platform: state
        entity_id: !input motion_sensors
        to: "off"
        for: !input no_motion_wait
    timeout:
      hours: 24
    continue_on_timeout: false
  - service: homeassistant.turn_off
    target: !input target_lights
